obj-$(CONFIG_LEARNING_MODULES)		+= module01.o
obj-$(CONFIG_LEARNING_MODULES)		+= module02.o
obj-$(CONFIG_LEARNING_MODULES)		+= module03a.o
obj-$(CONFIG_LEARNING_MODULES)		+= module03b.o
obj-$(CONFIG_LEARNING_MODULES)		+= module04.o
obj-$(CONFIG_LEARNING_MODULES)		+= module05.o
obj-$(CONFIG_LEARNING_MODULES)		+= module06.o
